import re

FORBIDDEN_KEYWORDS = [
    "INSERT", "UPDATE", "DELETE", "DROP", "ALTER",
    "CREATE", "TRUNCATE", "REPLACE", "ATTACH", "DETACH"
]

def sanitize_and_validate_sql(raw_sql: str) -> tuple[bool, str]:
    """
    Cleans markdown formatting and verifies that the query is a read-only SELECT/WITH statement.
    Returns (is_valid, cleaned_sql_or_error_message).
    """
    # Remove markdown code block syntax if generated by LLM
    cleaned = raw_sql.strip()
    cleaned = re.sub(r"^```sql\s*", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"^```\s*", "", cleaned)
    cleaned = re.sub(r"\s*```$", "", cleaned)
    cleaned = cleaned.strip().rstrip(";")

    # Check for valid query starting words
    upper_query = cleaned.upper()
    if not (upper_query.startswith("SELECT") or upper_query.startswith("WITH")):
        return False, "Security Error: Only SELECT queries are permitted."

    # Reject forbidden state-mutating keywords
    for keyword in FORBIDDEN_KEYWORDS:
        pattern = r"\b" + keyword + r"\b"
        if re.search(pattern, upper_query):
            return False, f"Security Violation: Query contains prohibited operation '{keyword}'."

    return True, cleaned